name: Build & Deploy to yev.vision/aural
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: wp13874980.server-he.de
          username: ftp13874980-aural
          password: aural33!
          port: 21
          protocol: ftps
          local-dir: ./dist/
          server-dir: /www/aural/
          dangerous-clean-slate: false
          log-level: standard
